import { describe, expect, it } from 'vitest';
import fixture from '../../pipeline/tests/fixtures/whatif_fixture.json';
import expected from '../../pipeline/tests/fixtures/whatif_expected.json';
import { ParkMillerRng, median, monteCarlo, simulateRace, validateParams } from './whatifModel.js';

// Parity contract with pipeline/models/whatif.py: both implementations
// run the same committed fixture and are pinned to the same expected
// file (generated by the Python reference). 1e-9 s tolerance on ~5500 s
// totals is effectively bit-equality — that's the point.
describe('whatif parity with the Python reference', () => {
  it('monteCarlo matches the committed expected output', () => {
    const totals = monteCarlo(fixture);

    expect(totals).toHaveLength(expected.iterations);
    expected.first_totals_s.forEach((want, i) => {
      expect(Math.abs(totals[i] - want)).toBeLessThan(1e-9);
    });
    expect(Math.abs(totals[totals.length - 1] - expected.last_total_s)).toBeLessThan(1e-9);
    expect(Math.abs(median(totals) - expected.median_total_s)).toBeLessThan(1e-9);
  });

  it('RNG stream is deterministic and in [0, 1)', () => {
    const a = new ParkMillerRng(12345);
    const b = new ParkMillerRng(12345);
    for (let i = 0; i < 1000; i++) {
      const u = a.next();
      expect(u).toBe(b.next());
      expect(u).toBeGreaterThanOrEqual(0);
      expect(u).toBeLessThan(1);
    }
  });

  it('simulateRace produces one time per lap and places the pit loss on the in-lap', () => {
    const rates = fixture.strategy.map((s) => fixture.compounds[s.compound].deg_rate_s_per_lap);
    const result = simulateRace(fixture, rates, [fixture.pit_loss_s]);

    expect(result.lap_times).toHaveLength(fixture.total_laps);
    const sum = result.lap_times.reduce((acc, t) => acc + t, 0);
    expect(Math.abs(sum - result.total_time_s)).toBeLessThan(1e-9);
    expect(result.lap_times[19] - result.lap_times[20]).toBeGreaterThan(fixture.pit_loss_s * 0.9);
  });

  it('validateParams rejects a strategy that does not cover the race distance', () => {
    const bad = structuredClone(fixture);
    bad.strategy[0].laps += 1;
    expect(() => validateParams(bad)).toThrow(/58 laps/);
  });
});
