import { useEffect, useMemo, useState } from 'react';
import { dataPath } from '../lib/dataPath.js';
import EmptyState from '../components/EmptyState.jsx';
import TrackMap from '../components/TrackMap.jsx';

// M1 — Circuit Atlas. The outline is a real driven lap: the position
// trace of the fastest race lap, in metres, thinned but not smoothed.
// It is not a drawing of the circuit and does not claim to be — it
// follows the racing line, which is where a car actually went, and the
// page says so rather than letting a reader assume a survey.
//
// Corner numbering and DRS zones stay absent. The position source
// publishes neither, and numbering corners from memory would be exactly
// the kind of invented detail that looks finished.

export default function CircuitAtlas() {
  const [state, setState] = useState({ status: 'loading', season: null });
  const [selected, setSelected] = useState('');
  const [circuit, setCircuit] = useState({ status: 'idle', data: null });

  useEffect(() => {
    let cancelled = false;
    fetch(dataPath('season.json'))
      .then((res) => {
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        return res.json();
      })
      .then((season) => {
        if (cancelled) return;
        setState({ status: 'ready', season });
        const today = new Date().toISOString().slice(0, 10);
        const run = season.calendar.filter((r) => r.date <= today);
        if (run.length > 0) setSelected(run[run.length - 1].circuitId);
      })
      .catch(() => {
        if (!cancelled) setState({ status: 'empty', season: null });
      });
    return () => {
      cancelled = true;
    };
  }, []);

  useEffect(() => {
    if (!selected) return undefined;
    let cancelled = false;
    setCircuit({ status: 'loading', data: null });
    fetch(dataPath(`circuits/${selected}.json`))
      .then((res) => {
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        return res.json();
      })
      .then((data) => {
        if (!cancelled) setCircuit({ status: 'ready', data });
      })
      .catch(() => {
        if (!cancelled) setCircuit({ status: 'empty', data: null });
      });
    return () => {
      cancelled = true;
    };
  }, [selected]);

  const runRounds = useMemo(() => {
    if (!state.season) return [];
    const today = new Date().toISOString().slice(0, 10);
    return state.season.calendar.filter((r) => r.date <= today);
  }, [state.season]);

  if (state.status === 'loading') {
    return <EmptyState title="Loading calendar…" reason="Fetching public/data/season.json." />;
  }

  if (state.status === 'empty') {
    return (
      <EmptyState
        title="No calendar published yet"
        reason="season.json has not been generated by the refresh-data workflow yet."
      />
    );
  }

  const today = new Date().toISOString().slice(0, 10);
  const doc = circuit.data;
  const scale = doc?.positionUnitsPerMetre;

  return (
    <section className="page">
      <header className="page-head">
        <h1>Circuit Atlas</h1>
        <p className="page-sub">
          Track outlines traced from real position telemetry — each one a lap somebody
          actually drove.
        </p>
        <p className="mono generated-at">generated {state.season.generated_at}</p>
      </header>

      {runRounds.length > 0 && (
        <div className="driver-picker">
          {runRounds.map((round) => (
            <button
              key={round.circuitId}
              type="button"
              className={`driver-chip${selected === round.circuitId ? ' is-on' : ''}`}
              onClick={() => setSelected(round.circuitId)}
            >
              <span className="mono">R{round.round}</span>
              <span className="legend-fullname">{round.circuitName}</span>
            </button>
          ))}
        </div>
      )}

      {circuit.status === 'loading' && (
        <EmptyState title="Loading circuit…" reason={`Fetching circuits/${selected}.json.`} />
      )}

      {circuit.status === 'empty' && (
        <EmptyState
          title="No geometry for this circuit yet"
          reason="The refresh writes a circuit outline from the race's position trace. This round has not been processed yet, or its position data could not be fetched."
        />
      )}

      {circuit.status === 'ready' && doc && (
        <section className="panel">
          <div className="panel-head">
            <h2>{doc.circuitName}</h2>
            <p className="panel-note">{doc.source}</p>
          </div>

          <div className="track-map-wrap">
            <TrackMap outline={doc.outline} corners={doc.corners ?? []} />
          </div>

          <div className="figure-grid">
            <div className="figure">
              <p className="figure-label">Outline points</p>
              <p className="figure-value mono">{doc.outline?.length ?? 0}</p>
              <p className="figure-sample">position samples along one lap</p>
            </div>
            {scale && (
              <div className="figure">
                <p className="figure-label">Position unit</p>
                <p className="figure-value mono">{Number(scale.value).toFixed(2)}</p>
                <p className="figure-sample">
                  raw units per metre, over {scale.sample_size} samples
                </p>
                <p className="figure-note">{scale.source}</p>
              </div>
            )}
          </div>

          {doc.limitations?.length > 0 && (
            <ul className="reason-list">
              {doc.limitations.map((line) => (
                <li key={line}>{line}</li>
              ))}
            </ul>
          )}
        </section>
      )}

      <div className="table-scroll is-full">
        <table>
          <caption className="visually-hidden">{state.season.year} race calendar</caption>
          <thead>
            <tr>
              <th scope="col" className="tabular">Rd</th>
              <th scope="col">Grand Prix</th>
              <th scope="col">Circuit</th>
              <th scope="col" className="tabular">Date</th>
              <th scope="col">Format</th>
            </tr>
          </thead>
          <tbody>
            {state.season.calendar.map((round) => (
              <tr key={round.round} className={round.date > today ? 'is-muted' : ''}>
                <td className="tabular">{String(round.round).padStart(2, '0')}</td>
                <td>{round.raceName}</td>
                <td className="team-cell">{round.circuitName}</td>
                <td className="tabular">{round.date}</td>
                <td>
                  {round.sprint ? <span className="tag">sprint</span> : ''}
                  {round.date > today && <span className="tag tag-quiet">upcoming</span>}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </section>
  );
}
