import { useEffect, useState } from 'react';
import { dataPath } from '../lib/dataPath.js';
import EmptyState from '../components/EmptyState.jsx';

// M2 — Season Ledger. Standings are computed by the pipeline and
// cross-checked against the API at export time (docs/SPEC.md); this page
// only renders what was written to public/data/standings.json. It never
// computes or guesses a standing itself.
export default function SeasonLedger() {
  const [state, setState] = useState({ status: 'loading', data: null, error: null });

  useEffect(() => {
    let cancelled = false;
    fetch(dataPath('standings.json'))
      .then((res) => {
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        return res.json();
      })
      .then((data) => {
        if (!cancelled) setState({ status: 'ready', data, error: null });
      })
      .catch((error) => {
        if (!cancelled) setState({ status: 'empty', data: null, error });
      });
    return () => {
      cancelled = true;
    };
  }, []);

  if (state.status === 'loading') {
    return <EmptyState title="Loading standings…" reason="Fetching public/data/standings.json." />;
  }

  if (state.status === 'empty') {
    return (
      <EmptyState
        title="No standings published yet"
        reason="standings.json has not been generated by the refresh-data workflow yet. It runs on a Tuesday cron and on manual dispatch, and commits real data pulled from Jolpica-F1 once at least one 2026 round has results."
      />
    );
  }

  const { standings, generated_at, source_check } = state.data;

  return (
    <section>
      <h1>Season Ledger</h1>
      <p className="mono generated-at">Generated {generated_at}</p>
      {source_check?.mismatch && (
        <div className="warning-banner" role="alert">
          Computed standings disagree with the Jolpica-F1 standings endpoint
          for this round — showing the locally computed table pending
          investigation. See source_check in standings.json for details.
        </div>
      )}
      <table>
        <thead>
          <tr>
            <th>Pos</th>
            <th>Driver</th>
            <th>Team</th>
            <th className="tabular">Points</th>
          </tr>
        </thead>
        <tbody>
          {standings.map((row) => (
            <tr key={row.driverCode}>
              <td>{row.position}</td>
              <td>{row.driverName}</td>
              <td>{row.team}</td>
              <td className="tabular">{row.points}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </section>
  );
}
