import { useEffect, useState } from 'react';
import { dataPath } from '../lib/dataPath.js';
import EmptyState from '../components/EmptyState.jsx';

// M2 — Season Ledger. Standings are computed by the pipeline and
// cross-checked against the API at export time (docs/SPEC.md); this page
// only renders what was written to public/data/standings.json. It never
// computes or guesses a standing itself.
export default function SeasonLedger() {
  const [state, setState] = useState({ status: 'loading', data: null, error: null });

  useEffect(() => {
    let cancelled = false;
    fetch(dataPath('standings.json'))
      .then((res) => {
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        return res.json();
      })
      .then((data) => {
        if (!cancelled) setState({ status: 'ready', data, error: null });
      })
      .catch((error) => {
        if (!cancelled) setState({ status: 'empty', data: null, error });
      });
    return () => {
      cancelled = true;
    };
  }, []);

  if (state.status === 'loading') {
    return <EmptyState title="Loading standings…" reason="Fetching public/data/standings.json." />;
  }

  if (state.status === 'empty') {
    return (
      <EmptyState
        title="No standings published yet"
        reason="standings.json has not been generated by the refresh-data workflow yet. It runs on a Tuesday cron and on manual dispatch, and commits real data pulled from Jolpica-F1 once at least one 2026 round has results."
      />
    );
  }

  const { standings, generated_at, source_check } = state.data;
  const leaderPoints = standings.length > 0 ? standings[0].points : 0;

  return (
    <section className="page">
      <header className="page-head">
        <h1>Season Ledger</h1>
        <p className="page-sub">
          Points accumulated independently from each round's results, then cross-checked
          against the published standings before publishing.
        </p>
        <p className="mono generated-at">generated {generated_at}</p>
      </header>

      {source_check?.mismatch ? (
        <div className="warning-banner" role="alert">
          <strong>Cross-check failed.</strong> This table and the Jolpica-F1 standings
          endpoint disagree for {source_check.details?.length ?? 0} driver(s). One of them
          is wrong and this page cannot tell which, so treat every figure below as
          unverified until it is resolved.
        </div>
      ) : (
        <p className="verified-note">
          Cross-check passed: every position and points total matches the published
          standings.
        </p>
      )}

      <table className="ledger-table">
        <thead>
          <tr>
            <th scope="col" className="tabular">Pos</th>
            <th scope="col">Driver</th>
            <th scope="col">Team</th>
            <th scope="col" className="tabular">Wins</th>
            <th scope="col" className="tabular">Points</th>
            <th scope="col">Gap to leader</th>
          </tr>
        </thead>
        <tbody>
          {standings.map((row) => (
            <tr key={row.driverCode}>
              <td className="tabular">{row.position}</td>
              <td>
                <span className="mono driver-code">{row.driverCode ?? '—'}</span>{' '}
                {row.driverName}
              </td>
              <td className="team-cell">{row.team}</td>
              <td className="tabular">{row.wins > 0 ? row.wins : '—'}</td>
              <td className="tabular points-cell">{row.points}</td>
              <td>
                {/* Bar length is the points total against the leader's —
                    magnitude, so a bar; the number is right there beside
                    it, so the bar carries no label of its own. */}
                <span className="gap-bar-wrap" aria-hidden="true">
                  <span
                    className="gap-bar"
                    style={{
                      width: leaderPoints > 0 ? `${(row.points / leaderPoints) * 100}%` : '0%',
                    }}
                  />
                </span>
                <span className="tabular gap-value">
                  {row.position === 1 ? '—' : `-${(leaderPoints - row.points).toFixed(0)}`}
                </span>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </section>
  );
}
