import { useEffect, useState } from 'react';
import { dataPath } from '../lib/dataPath.js';
import { MAX_SERIES, seriesColor } from '../theme/palette.js';
import EmptyState from '../components/EmptyState.jsx';
import ProgressionChart from '../components/ProgressionChart.jsx';
import { Method } from '../components/Disclosure.jsx';

// M2 — Season Ledger. Standings are computed by the pipeline and
// cross-checked against the API at export time (docs/SPEC.md); this page
// only renders what was written to public/data/standings.json. It never
// computes or guesses a standing itself.
export default function SeasonLedger() {
  const [state, setState] = useState({ status: 'loading', data: null, error: null });
  const [selected, setSelected] = useState([]);

  useEffect(() => {
    let cancelled = false;
    fetch(dataPath('standings.json'))
      .then((res) => {
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        return res.json();
      })
      .then((data) => {
        if (cancelled) return;
        setState({ status: 'ready', data, error: null });
        // Open on the current top of the table rather than an empty
        // chart — the championship fight is the default question.
        setSelected(data.standings.slice(0, 3).map((r) => r.driverCode));
      })
      .catch((error) => {
        if (!cancelled) setState({ status: 'empty', data: null, error });
      });
    return () => {
      cancelled = true;
    };
  }, []);

  if (state.status === 'loading') {
    return <EmptyState title="Loading standings…" reason="Fetching public/data/standings.json." />;
  }

  if (state.status === 'empty') {
    return (
      <EmptyState
        title="No standings published yet"
        reason="standings.json has not been generated by the refresh-data workflow yet. It runs on a Tuesday cron and on manual dispatch, and commits real data pulled from Jolpica-F1 once at least one 2026 round has results."
      />
    );
  }

  const { standings, generated_at, source_check, progression, elimination } = state.data;
  const leaderPoints = standings.length > 0 ? standings[0].points : 0;
  const nameByCode = new Map(standings.map((r) => [r.driverCode, r.driverName]));

  const progressionSeries = selected.map((code, i) => ({
    code,
    name: nameByCode.get(code) ?? code,
    color: seriesColor(i),
  }));

  const eliminatedCount = elimination
    ? Object.values(elimination.drivers).filter((d) => d.eliminated).length
    : 0;

  return (
    <section className="page">
      <header className="page-head">
        <h1>Season Ledger</h1>
        <p className="page-sub">
          Points accumulated independently from each round's results, then cross-checked
          against the published standings before publishing.
        </p>
        <p className="mono generated-at">generated {generated_at}</p>
      </header>

      {source_check?.mismatch ? (
        <div className="warning-banner" role="alert">
          <strong>Cross-check failed.</strong> This table and the Jolpica-F1 standings
          endpoint disagree for {source_check.details?.length ?? 0} driver(s). One of them
          is wrong and this page cannot tell which, so treat every figure below as
          unverified until it is resolved.
        </div>
      ) : (
        <p className="verified-note">
          Cross-check passed: every position and points total matches the published
          standings.
        </p>
      )}

      {progression && progression.length > 0 && (
        <section className="panel">
          <div className="panel-head">
            <h2>Points progression</h2>
            <p className="panel-note">
              Cumulative points after each completed round. Select up to {MAX_SERIES}{' '}
              drivers.
            </p>
          </div>

          <div className="driver-picker">
            {standings.slice(0, 12).map((row) => {
              const idx = selected.indexOf(row.driverCode);
              const isOn = idx >= 0;
              return (
                <label
                  key={row.driverCode}
                  className={`driver-chip${isOn ? ' is-on' : ''}`}
                  style={isOn ? { borderColor: seriesColor(idx) } : undefined}
                >
                  <input
                    type="checkbox"
                    checked={isOn}
                    disabled={!isOn && selected.length >= MAX_SERIES}
                    onChange={(e) =>
                      setSelected((prev) =>
                        e.target.checked
                          ? [...prev, row.driverCode]
                          : prev.filter((c) => c !== row.driverCode),
                      )
                    }
                  />
                  {isOn && (
                    <span
                      className="legend-swatch"
                      style={{ background: seriesColor(idx) }}
                      aria-hidden="true"
                    />
                  )}
                  <span className="mono">{row.driverCode}</span>
                </label>
              );
            })}
          </div>

          {progressionSeries.length === 0 ? (
            <EmptyState
              title="No drivers selected"
              reason="Pick a driver above to plot their points across the season."
            />
          ) : (
            <>
              <ProgressionChart progression={progression} series={progressionSeries} />
              <div className="chart-legend">
                {progressionSeries.map((s) => (
                  <span key={s.code} className="legend-item">
                    <span
                      className="legend-swatch"
                      style={{ background: s.color }}
                      aria-hidden="true"
                    />
                    <span className="mono">{s.code}</span>
                    <span className="legend-fullname">{s.name}</span>
                  </span>
                ))}
              </div>
            </>
          )}
        </section>
      )}

      {elimination && elimination.remainingRounds > 0 && (
        <div className="verified-note">
          <p>
            {eliminatedCount === 0 ? (
              <>No driver is mathematically out of the championship yet.</>
            ) : (
              <>
                <strong>{eliminatedCount}</strong> of {standings.length} drivers can no
                longer win the championship.
              </>
            )}{' '}
            {elimination.remainingRounds} round
            {elimination.remainingRounds === 1 ? '' : 's'} left, worth at most{' '}
            <span className="mono">{elimination.remainingMaxPoints}</span> points.
          </p>
          <Method label="How elimination is decided">
            A driver is counted out only when taking every remaining point still leaves them
            behind the leader's current{' '}
            <span className="mono">{elimination.leaderPoints}</span> — even if the leader
            never scores again. A driver who could draw level is not counted out.
          </Method>
        </div>
      )}

      <section className="panel">
        <div className="panel-head">
          <h2>The championship as it stands</h2>
          <p className="panel-note">
            Accumulated from each round's results, not copied from the published table. The
            cross-check above is what says the two agree.
          </p>
        </div>
        <div className="table-scroll is-full">
          <table className="ledger-table">
        <thead>
          <tr>
            <th scope="col" className="tabular">Pos</th>
            <th scope="col">Driver</th>
            <th scope="col" className="hide-md">Team</th>
            <th scope="col" className="tabular hide-sm">Wins</th>
            <th scope="col" className="tabular">Points</th>
            <th scope="col">
              <span className="label-lg">Gap to leader</span>
              <span className="label-sm">Gap</span>
            </th>
          </tr>
        </thead>
        <tbody>
          {standings.map((row) => (
            <tr key={row.driverCode}>
              <td className="tabular">{row.position}</td>
              <td>
                <span className="mono driver-code">{row.driverCode ?? '—'}</span>{' '}
                <span className="driver-fullname">{row.driverName}</span>
                {elimination?.drivers?.[row.driverCode]?.eliminated && (
                  <span
                    className="tag tag-quiet"
                    title={`Even winning every remaining round (max ${elimination.remainingMaxPoints} points) would leave them short of the leader's current ${elimination.leaderPoints}`}
                  >
                    out
                  </span>
                )}
              </td>
              <td className="team-cell hide-md">{row.team}</td>
              <td className="tabular hide-sm">{row.wins > 0 ? row.wins : '—'}</td>
              <td className="tabular points-cell">{row.points}</td>
              <td>
                {/* Bar length is the points total against the leader's —
                    magnitude, so a bar; the number is right there beside
                    it, so the bar carries no label of its own. */}
                <span className="gap-bar-wrap" aria-hidden="true">
                  <span
                    className="gap-bar"
                    style={{
                      width: leaderPoints > 0 ? `${(row.points / leaderPoints) * 100}%` : '0%',
                    }}
                  />
                </span>
                <span className="tabular gap-value">
                  {row.position === 1 ? '—' : `-${(leaderPoints - row.points).toFixed(0)}`}
                </span>
              </td>
            </tr>
          ))}
          </tbody>
          </table>
        </div>
      </section>
    </section>
  );
}
