import { useEffect, useState } from 'react';
import { dataPath } from '../lib/dataPath.js';
import EmptyState from '../components/EmptyState.jsx';

// M6 — Upcoming Race Brief. Everything on this page is a record of past
// editions of the circuit the next round visits. Nothing here is a
// prediction, and the page says so at the top rather than in a footnote:
// the 2026 regulation reset changed the cars, so a median from 2022-2025
// describes those cars at this track, not the ones about to race.
//
// Every figure is rendered next to the sample it came from. A median
// from two editions and a median from ten read identically as a number,
// and the reader cannot tell them apart unless the count is shown.

function Figure({ label, value, sample, note }) {
  return (
    <div className="figure">
      <p className="figure-label">{label}</p>
      <p className="figure-value mono">{value ?? '—'}</p>
      <p className="figure-sample">{sample}</p>
      {note && <p className="figure-note">{note}</p>}
    </div>
  );
}

function formatDate(iso) {
  // Parsed as UTC rather than local: a race date is a calendar date, and
  // letting the browser shift it by a timezone would show the wrong day
  // to readers west of UTC.
  const d = new Date(`${iso}T00:00:00Z`);
  return d.toLocaleDateString(undefined, {
    weekday: 'long', day: 'numeric', month: 'long', year: 'numeric', timeZone: 'UTC',
  });
}

export default function UpcomingBrief() {
  const [state, setState] = useState({ status: 'loading', data: null });

  useEffect(() => {
    let cancelled = false;
    fetch(dataPath('upcoming.json'))
      .then((res) => {
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        return res.json();
      })
      .then((data) => !cancelled && setState({ status: 'ready', data }))
      .catch(() => !cancelled && setState({ status: 'empty', data: null }));
    return () => {
      cancelled = true;
    };
  }, []);

  if (state.status === 'loading') {
    return <EmptyState title="Loading brief…" reason="Fetching public/data/upcoming.json." />;
  }

  if (state.status === 'empty') {
    return (
      <EmptyState
        title="No brief published yet"
        reason="upcoming.json has not been generated by the refresh-data workflow yet. It is written on every refresh from the published calendar and past editions of the next round's circuit."
      />
    );
  }

  const { next, history, generated_at, historyYearsRequested, reason } = state.data;

  if (!next) {
    return (
      <EmptyState
        title="No round left to preview"
        reason={reason ?? 'Every round on the published calendar has been run.'}
      />
    );
  }

  const finish = history?.finishRate;
  const finishPct =
    finish && finish.share != null ? `${(finish.share * 100).toFixed(0)}%` : null;

  return (
    <section className="page">
      <header className="page-head">
        <h1>Upcoming: {next.raceName}</h1>
        <p className="page-sub">
          Round {next.round} · {next.circuitName} · {formatDate(next.date)}
          {next.sprint ? ' · sprint weekend' : ''}
        </p>
        <p className="mono generated-at">generated {generated_at}</p>
      </header>

      <div className="warning-banner" role="note">
        <strong>These are records, not forecasts.</strong> Every figure below counts what
        happened at this circuit in earlier seasons. 2026 is the first year of a new set
        of technical regulations, so the cars that set these numbers are not the cars
        about to race — treat the priors as weak, and read the sample count under each
        one before leaning on it.
      </div>

      {!history || history.editions === 0 ? (
        <EmptyState
          title="No past editions available"
          reason={
            reason ??
            `No results were published for this circuit in ${
              historyYearsRequested?.join(', ') ?? 'the seasons queried'
            }, so there is no prior to show. A first-time or returning venue has no history to draw on.`
          }
        />
      ) : (
        <>
          <section className="panel">
            <div className="panel-head">
              <h2>Priors from past editions</h2>
              <p className="panel-note">
                Computed from {history.editions} edition
                {history.editions === 1 ? '' : 's'} of this circuit
                {history.years?.length ? ` (${history.years.join(', ')})` : ''}.
              </p>
            </div>

            <div className="figure-grid">
              <Figure
                label="Cars classified at the finish"
                value={finishPct}
                sample={
                  finish
                    ? `${finish.classified} of ${finish.starters} starters`
                    : 'no data'
                }
                note="Classified means positionText carried a finishing position; cars that never started are not counted as starters."
              />
              <Figure
                label="Median places moved from grid"
                value={
                  history.positionChange.medianPlaces != null
                    ? history.positionChange.medianPlaces.toFixed(1)
                    : null
                }
                sample={`${history.positionChange.n} classified finishes`}
                note={history.positionChange.note}
              />
              <Figure
                label="Median winner's grid slot"
                value={
                  history.winnerGrid.median != null
                    ? `P${history.winnerGrid.median}`
                    : null
                }
                sample={`${history.winnerGrid.n} winner${history.winnerGrid.n === 1 ? '' : 's'}`}
                note={
                  history.winnerGrid.best != null
                    ? `Best P${history.winnerGrid.best}, worst P${history.winnerGrid.worst}.`
                    : undefined
                }
              />
              <Figure
                label="Median stops per driver"
                value={
                  history.stops.medianPerDriver != null
                    ? history.stops.medianPerDriver.toFixed(1)
                    : null
                }
                sample={
                  history.stops.editionsWithData > 0
                    ? `${history.stops.n} drivers across ${history.stops.editionsWithData} edition${history.stops.editionsWithData === 1 ? '' : 's'}`
                    : 'no stop data available'
                }
              />
            </div>
          </section>

          <section className="panel">
            <div className="panel-head">
              <h2>Edition by edition</h2>
              <p className="panel-note">
                The medians above come from these rows. A prior drawn from editions that
                disagree with each other is a weaker claim than the single number suggests,
                which is why the rows are here.
              </p>
            </div>
            <div className="table-scroll table-compact">
              <table>
                <thead>
                  <tr>
                    <th scope="col" className="tabular">Year</th>
                    <th scope="col" className="tabular">Classified</th>
                    <th scope="col" className="tabular">Starters</th>
                    <th scope="col" className="tabular">Winner from</th>
                    <th scope="col" className="tabular">Median stops</th>
                  </tr>
                </thead>
                <tbody>
                  {history.perEdition.map((e) => (
                    <tr key={e.year}>
                      <td className="tabular">{e.year}</td>
                      <td className="tabular">{e.classified}</td>
                      <td className="tabular">{e.starters}</td>
                      <td className="tabular">{e.winnerGrid ? `P${e.winnerGrid}` : '—'}</td>
                      <td className="tabular">
                        {e.medianStops != null ? e.medianStops.toFixed(1) : '—'}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </section>

          <section className="panel">
            <div className="panel-head">
              <h2>Not available</h2>
              <p className="panel-note">
                Priors a brief like this would normally carry, and why this one does not.
                Listing them is the point: an absent section reads as an oversight, a named
                gap reads as a limit of the source.
              </p>
            </div>
            <ul className="reason-list">
              {Object.entries(history.unavailable ?? {}).map(([key, why]) => (
                <li key={key}>
                  <span className="mono">{key}</span> — {why}
                </li>
              ))}
            </ul>
          </section>
        </>
      )}
    </section>
  );
}
